### ISSUE TITLE
fix apple clang github action workflow

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#534]
ref: https://github.com/cieslarmichal/faker-cxx/actions/runs/8909259438/job/24468520339

```
CMake Error at CMakeLists.txt:4 (project):
  The CMAKE_CXX_COMPILER:

    /usr/local/opt/llvm@16/bin/clang++

  is not a full path to an existing compiler tool.
  ```
  
  Probably need to fix that path

**Comment by AdamJovanovic** [comment]
I'll give this one a go, I just need to find a way to test what I'm changing. It's interesting to me that the pipeline would have broken between https://github.com/cieslarmichal/faker-cxx/commit/8899000ce2855fc29dc7cba6cd51ccaed5aa6567 and https://github.com/cieslarmichal/faker-cxx/commit/69524c97398a59a8ce5b40be8ce11b4c48414dcf

I'll start by checking that clang is added to the PATH correctly, since the `Install Clang` step does a `which clang++` and this returns `/usr/bin/clang++`, instead of the correct one at `/opt/homebrew/opt/llvm@16/bin/clang++`

As part of this, it would make sense to have the CMAKE option use `-DCMAKE_CXX_COMPILER=clang++`, and rely on the PATH instead of hard-coding

**Comment by AdamJovanovic** [comment]
Actually, the runner version changed somehow between those two commits.
PASSING pipeline uses:
```Current runner version: '2.315.0'
Operating System
  macOS
  12.7.4
  21H1123
```
FAILING pipeline uses:
```
Current runner version: '2.316.0'
Operating System
  macOS
  14.4.1
  23E224
```

**Comment by cieslarmichal** [comment]
Nice catch, the reason is we use macos-latest in https://github.com/cieslarmichal/faker-cxx/blob/main/.github/workflows/macos-clang-build.yml

The solution for this problem would be to fix path to work with latest and pin macos version in pipeline config in file above.

**Comment by AdamJovanovic** [comment]
PR opened :smile:
