### ISSUE TITLE
add missing tests for phone module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#811]
https://app.codecov.io/github/cieslarmichal/faker-cxx/blob/main/src%2Fmodules%2Fphone%2Fphone.cpp

**Comment by 00thirdeye00** [comment]
it would be good idea to change function names since [this](https://github.com/cieslarmichal/faker-cxx/blob/fc2f44f65052d4b5bc316fffac65b547692f94e0/include/faker-cxx/phone.h#L25) and [this](https://github.com/cieslarmichal/faker-cxx/blob/fc2f44f65052d4b5bc316fffac65b547692f94e0/include/faker-cxx/phone.h#L71) have same declaration. calling `number()` without parameters would call the first function not the later one.

**Comment by cieslarmichal** [comment]
ok it could be phoneNumberByFormat and phoneNumberByCountry

**Comment by 00thirdeye00** [comment]
@cieslarmichal , `phoneNumberByCountry` is a parameterized function. How to call it without `argument`?
