### ISSUE TITLE
add locale to word module

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#903]
ref book module

**Comment by gustavobastian** [comment]
Hi  @cieslarmichal, I would like to collaborate on this issue. After looking the code (the books and words modules), I noticed that right now this generate only English words . I am thinking in generate the Spanish(ARG) arrays in the word_store.h, new functions and tests. If it's ok(only for Spanish and English locations), please assign it to me.

**Comment by cieslarmichal** [comment]
Yeah you can do only with those two locales and it locale doesnt exist return default english

**Comment by gustavobastian** [comment]
Hi @cieslarmichal, I've done something (added to word module es_AR)... how could I get a code review? Just generate a pull request? If everything is ok, I will continue with another languages. I am considering using std::vector instead of std::array in the structures in "word_store.h".

**Comment by cieslarmichal** [comment]
@gustavobastian yup just generate a PR, why would you like to change it to vector?

**Comment by gustavobastian** [comment]
I am generating a map with the key each faker::Locale, and the value, the array. If we use const vector, instead of const array, we can let the compiler to calculate the size of each language structure. Right now, we are forced to store the same number of words for each language, and I don´t know if other languages has enough words for each kind, as the map is (key,array<string_view>xxx):

![Screenshot from 2024-09-30 13-14-28](https://github.com/user-attachments/assets/3f3eeb93-d499-4626-8119-1018a1c97147)

We can repeat some words in order to get the desired number... There are multiple solutions for the situation.
