### ISSUE TITLE
fix codecov in person test

### ISSUE THREAD

**Issue by cieslarmichal** [cieslarmichal/faker-cxx#909]
![image](https://github.com/user-attachments/assets/50caf7ce-267d-4dbb-b354-9c6e8ff4efb8)

**Comment by MichaScant** [comment]
Hey @cieslarmichal, can I be assigned to this issue?

**Comment by cieslarmichal** [comment]
Yeah, assigned

**Comment by MichaScant** [comment]
Hello @cieslarmichal are there any errors with ASSERT_TRUE in person_test.cpp on your end?
In addition to the issue displayed on the screenshot, I've been getting the following errors throughout the file. 

Should I look into it as part of this issue or is it being handled as part of another?

<img width="1039" alt="Screenshot 2024-10-14 at 3 04 02 PM" src="https://github.com/user-attachments/assets/2d8dfb05-75a0-4139-be0e-a8ead5b83494">

**Comment by cieslarmichal** [comment]
It should not have any errors, build project first, maybe you dont have c++ compiler?

**Comment by MichaScant** [comment]
Hey @cieslarmichal, unsure why the errors are occurring, I do have a compiler (using Apple Clang version 19.1.1), and my C++ is up to date (version 23). I have rebuilt the project with different compilers and C++ versions in case that is an issue, however, the errors are not disappearing. Since there are no errors on the build or when I run the tests, however, I assume it's an issue with the build settings on my end.

For context here is the error that occurs
<img width="749" alt="Screenshot 2024-10-15 at 10 23 05 AM" src="https://github.com/user-attachments/assets/2c6f1b69-546b-42cd-bc56-07f3fb6929fa">

**Comment by MichaScant** [comment]
Still don't know why it is occurring, The build settings seem to match and nothing changed when reinstalling the program.

The original issue seems to be fixed in the meantime (errors from the screenshot in the issue are no longer appearing). I'll create the PR now.
